2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_setup.py:_flush():76] Configure stats pid to 2631868
2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_setup.py:_flush():76] Loading settings from /home/aurora/.config/wandb/settings
2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_setup.py:_flush():76] Loading settings from /home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/wandb/settings
2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'dynamics_model/new_model/train.py', 'program_abspath': '/home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/train.py', 'program': '/home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/train.py'}
2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_init.py:_log_setup():524] Logging user logs to /home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/wandb/run-20250505_042643-n5baotii/logs/debug.log
2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_init.py:_log_setup():525] Logging internal logs to /home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/wandb/run-20250505_042643-n5baotii/logs/debug-internal.log
2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_init.py:init():607] calling init triggers
2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {'seed': 42, 'train': {'batch_size': 1000, 'epochs': 20, 'learning_rate': 0.03, 'no_cuda': False, 'log_file': 'logs/train.log', 'num_workers': 4, 'checkpoint_dir': 'checkpoints', 'max_mask_prob': 0.0, 'mask_warmup_epochs': 10}, 'data': {'path': '/home/aurora/handful-of-trials-pytorch/pusht_dataset', 'n_rollout': 10000, 'normalize_action': True, 'split_ratio': 0.8, 'train_frac': 0.8, 'num_hist': 8, 'frameskip': 1, 'with_velocity': True, 'state_mean': [236.6155, 264.5674, 255.1307, 266.3721, 0.165, 0.6914, -2.93032027, 2.54307914], 'state_std': [101.1202, 87.0112, 52.7054, 57.4971, 0.4698, 0.5234, 74.84556075, 74.14009094]}, 'model': {'num_models': 5, 'state_dim': 8, 'action_dim': 2, 'embedding_dim': 4, 'n_heads': 2, 'n_layers': 2, 'feedforward_dim': 16, 'dropout': 0.1, 'mask_curriculum': {'max_mask_prob': 0.5, 'warmup_epochs': 10}, 'var_threshold': 0.25}, 'wandb': {'enable': True, 'project': 'gnn-dynamics', 'run_name': 'masked-dynamics-experiment'}}
2025-05-05 04:26:43,470 INFO    MainThread:2631868 [wandb_init.py:init():657] starting backend
2025-05-05 04:26:43,471 INFO    MainThread:2631868 [wandb_init.py:init():661] setting up manager
2025-05-05 04:26:43,472 INFO    MainThread:2631868 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-05 04:26:43,474 INFO    MainThread:2631868 [wandb_init.py:init():669] backend started and connected
2025-05-05 04:26:43,476 INFO    MainThread:2631868 [wandb_init.py:init():764] updated telemetry
2025-05-05 04:26:43,482 INFO    MainThread:2631868 [wandb_init.py:init():797] communicating run to backend with 90.0 second timeout
2025-05-05 04:26:43,705 INFO    MainThread:2631868 [wandb_run.py:_on_init():2479] communicating current version
2025-05-05 04:26:43,745 INFO    MainThread:2631868 [wandb_run.py:_on_init():2488] got version response upgrade_message: "wandb version 0.19.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-05-05 04:26:43,746 INFO    MainThread:2631868 [wandb_init.py:init():848] starting run threads in backend
2025-05-05 04:26:44,076 WARNING MainThread:2631868 [wandb_init.py:init():1229] interrupted
Traceback (most recent call last):
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1225, in init
    return wi.init()
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 861, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2025-05-05 04:26:53,464 WARNING MsgRouterThr:2631868 [router.py:message_loop():77] message_loop has been closed
