Loaded 100 rollouts
Loaded 100 rollouts
2025-04-17 05:48:23,232 INFO Epoch 1, Train Loss: 1.417404
2025-04-17 05:48:25,082 INFO Epoch 1, Val Loss: 0.885727
2025-04-17 05:48:25,110 INFO Saved checkpoint: checkpoints/model_epoch1.pt
2025-04-17 05:48:29,385 INFO Epoch 2, Train Loss: 1.150566
2025-04-17 05:48:31,265 INFO Epoch 2, Val Loss: 0.802099
2025-04-17 05:48:31,287 INFO Saved checkpoint: checkpoints/model_epoch2.pt
2025-04-17 05:48:35,716 INFO Epoch 3, Train Loss: 1.036483
2025-04-17 05:48:37,575 INFO Epoch 3, Val Loss: 0.771489
2025-04-17 05:48:37,599 INFO Saved checkpoint: checkpoints/model_epoch3.pt
2025-04-17 05:48:41,909 INFO Epoch 4, Train Loss: 0.962645
2025-04-17 05:48:43,785 INFO Epoch 4, Val Loss: 0.761419
2025-04-17 05:48:43,812 INFO Saved checkpoint: checkpoints/model_epoch4.pt
Traceback (most recent call last):
  File "/home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/train.py", line 132, in <module>
    main(sys.argv[1])
  File "/home/aurora/handful-of-trials-pytorch/dynamics_model/new_model/train.py", line 79, in main
    for batch in train_loader:
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1330, in _next_data
    idx, data = self._get_data()
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1296, in _get_data
    success, data = self._try_get_data()
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1134, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/aurora/anaconda3/envs/pusht/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt